In [ ]:
import numpy as np

# 1. SETUP DATA (Sesuai perhitungan sebelumnya)
n = 10
sum_y = 272
sum_x1 = 441
sum_x2 = 147
sum_x1y = 12005
sum_x2y = 4013
sum_x1_sq = 19461
sum_x2_sq = 2173
sum_x1x2 = 6485

print("=== LANGKAH 1: MENYUSUN MATRIKS UTAMA (A) DAN MATRIKS HASIL (B) ===")
# Matriks A berisi koefisien dari a, b1, b2
A = np.array([
    [n,      sum_x1,    sum_x2],
    [sum_x1, sum_x1_sq, sum_x1x2],
    [sum_x2, sum_x1x2,  sum_x2_sq]
])

# Matriks B berisi nilai di sisi kanan persamaan
B = np.array([sum_y, sum_x1y, sum_x2y])

print("Matriks A:\n", A)
print("\nMatriks B (Hasil):\n", B.reshape(3,1))
print("-" * 50)

# 2. MENYUSUN MATRIKS A1, A2, DAN A3
print("=== LANGKAH 2: MENYUSUN MATRIKS SUBSTITUSI (A1, A2, A3) ===")

# A1: Ganti kolom pertama Matriks A dengan Matriks B
A1 = A.copy()
A1[:, 0] = B

# A2: Ganti kolom kedua Matriks A dengan Matriks B
A2 = A.copy()
A2[:, 1] = B

# A3: Ganti kolom ketiga Matriks A dengan Matriks B
A3 = A.copy()
A3[:, 2] = B

print("Matriks A1 (Kolom 1 diganti B):\n", A1)
print("\nMatriks A2 (Kolom 2 diganti B):\n", A2)
print("\nMatriks A3 (Kolom 3 diganti B):\n", A3)
print("-" * 50)

# 3. MENGHITUNG DETERMINAN
print("=== LANGKAH 3: MENGHITUNG DETERMINAN ===")

det_A  = np.linalg.det(A)
det_A1 = np.linalg.det(A1)
det_A2 = np.linalg.det(A2)
det_A3 = np.linalg.det(A3)

print(f"det(A)  : {det_A:.2f}")
print(f"det(A1) : {det_A1:.2f}")
print(f"det(A2) : {det_A2:.2f}")
print(f"det(A3) : {det_A3:.2f}")
print("-" * 50)

# 4. MENGHITUNG NILAI a, b1, b2 (Aturan Cramer)
print("=== LANGKAH 4: MENGHITUNG PARAMETER (ATURAN CRAMER) ===")

a  = det_A1 / det_A
b1 = det_A2 / det_A
b2 = det_A3 / det_A

print(f"a  = det(A1) / det(A) = {det_A1:.2f} / {det_A:.2f} = {a:.4f}")
print(f"b1 = det(A2) / det(A) = {det_A2:.2f} / {det_A:.2f} = {b1:.4f}")
print(f"b2 = det(A3) / det(A) = {det_A3:.2f} / {det_A:.2f} = {b2:.4f}")
print("-" * 50)

print("\nKESIMPULAN AKHIR:")
print(f"Persamaan Regresi: Y = {a:.3f} + {b1:.3f}X1 + {b2:.3f}X2")

=== LANGKAH 1: MENYUSUN MATRIKS UTAMA (A) DAN MATRIKS HASIL (B) ===
Matriks A:
 [[   10   441   147]
 [  441 19461  6485]
 [  147  6485  2173]]

Matriks B (Hasil):
 [[  272]
 [12005]
 [ 4013]]
--------------------------------------------------
=== LANGKAH 2: MENYUSUN MATRIKS SUBSTITUSI (A1, A2, A3) ===
Matriks A1 (Kolom 1 diganti B):
 [[  272   441   147]
 [12005 19461  6485]
 [ 4013  6485  2173]]

Matriks A2 (Kolom 2 diganti B):
 [[   10   272   147]
 [  441 12005  6485]
 [  147  4013  2173]]

Matriks A3 (Kolom 3 diganti B):
 [[   10   441   272]
 [  441 19461 12005]
 [  147  6485  4013]]
--------------------------------------------------
=== LANGKAH 3: MENGHITUNG DETERMINAN ===
det(A)  : 1508.00
det(A1) : -20840.00
det(A2) : 850.00
det(A3) : 1658.00
--------------------------------------------------
=== LANGKAH 4: MENGHITUNG PARAMETER (ATURAN CRAMER) ===
a  = det(A1) / det(A) = -20840.00 / 1508.00 = -13.8196
b1 = det(A2) / det(A) = 850.00 / 1508.00 = 0.5637
b2 = det(A3) / det(A) = 16